# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium SA/NV
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

name: 'Setup Java and Maven Cache'
description: 'Sets up Temurin JDK 21 and enables the Maven dependency cache'

runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
      with:
        distribution: temurin
        java-version: '21'
        cache: maven

# Temporary : install the needed snapshot of open-rao
    - name: Checkout Open RAO
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        repository: powsybl/powsybl-open-rao
        ref: feature/cnec-creator-branch-names
        path: open-rao

    - name: Install Open RAO
      shell: bash
      working-directory: open-rao
      run: mvn -q -DskipTests clean install